- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello Message
      debug:
        msg: "Hello World!"
  tasks:
    - name: Fact
      debug:
        msg: {{ ansible_facts['nodename'] }}

